services:
  db:
    image: postgres:latest
    env_file: .env
    container_name: workshop_manager_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: workshop_manager_production
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d workshop_manager_production -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  rails:
    build: .
    container_name: workshop_manager_rails
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    environment:
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      DB_HOST: db
      DB_NAME: workshop_manager_production
      DB_USERNAME: postgres
      DB_PASSWORD: $POSTGRES_PASSWORD
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  sidekiq:
    build: .
    user: root
    env_file:
      - .env
    command: sh -c "bundle exec sidekiq"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  nginx:
    image: "nginx:latest"
    container_name: workshop_manager_nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl
    restart: unless-stopped
    depends_on:
      - rails
  redis:
    container_name: workshop_manager_redis
    image: bitnami/redis:6.2
    env_file:
      - .env
    volumes:
      - redis:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
      - 6379:6379
volumes:
  postgres_data: {}
  redis: {}
networks:
  default:
    name: workshop_manager
