require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/workshop_participants", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WorkshopParticipant. As you add validations to WorkshopParticipant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WorkshopParticipant.create! valid_attributes
      get workshop_participants_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      workshop_participant = WorkshopParticipant.create! valid_attributes
      get workshop_participant_url(workshop_participant)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_workshop_participant_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      workshop_participant = WorkshopParticipant.create! valid_attributes
      get edit_workshop_participant_url(workshop_participant)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WorkshopParticipant" do
        expect {
          post workshop_participants_url, params: { workshop_participant: valid_attributes }
        }.to change(WorkshopParticipant, :count).by(1)
      end

      it "redirects to the created workshop_participant" do
        post workshop_participants_url, params: { workshop_participant: valid_attributes }
        expect(response).to redirect_to(workshop_participant_url(WorkshopParticipant.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WorkshopParticipant" do
        expect {
          post workshop_participants_url, params: { workshop_participant: invalid_attributes }
        }.to change(WorkshopParticipant, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post workshop_participants_url, params: { workshop_participant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workshop_participant" do
        workshop_participant = WorkshopParticipant.create! valid_attributes
        patch workshop_participant_url(workshop_participant), params: { workshop_participant: new_attributes }
        workshop_participant.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the workshop_participant" do
        workshop_participant = WorkshopParticipant.create! valid_attributes
        patch workshop_participant_url(workshop_participant), params: { workshop_participant: new_attributes }
        workshop_participant.reload
        expect(response).to redirect_to(workshop_participant_url(workshop_participant))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        workshop_participant = WorkshopParticipant.create! valid_attributes
        patch workshop_participant_url(workshop_participant), params: { workshop_participant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workshop_participant" do
      workshop_participant = WorkshopParticipant.create! valid_attributes
      expect {
        delete workshop_participant_url(workshop_participant)
      }.to change(WorkshopParticipant, :count).by(-1)
    end

    it "redirects to the workshop_participants list" do
      workshop_participant = WorkshopParticipant.create! valid_attributes
      delete workshop_participant_url(workshop_participant)
      expect(response).to redirect_to(workshop_participants_url)
    end
  end
end
