name: RSpec CI

on:
  # allow running action manually
  workflow_dispatch:
  # trigger on push to master branch
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:latest
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://postgres:password@localhost:5432/rails_test'
    permissions:
      packages: read
    steps:
      - name: Create Folder
        run: |
          mkdir -p /opt/workshop_manager
          cd /opt/workshop_manager
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ruby and gems
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      - name: Bundle
        run: |
          bundle install
      - name: Pre-compile assets
        run: |
          bundle exec rails assets:precompile
      - name: set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run rspec
        run: |
          bundle exec rspec
