name: RSpec CI

on:
  # allow running action manually
  workflow_dispatch:
  # trigger on push to master branch
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:latest
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: workshop_manager_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://postgres:password@localhost:5432/workshop_manager_test'
    permissions:
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ruby and gems
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Bundle
        run: |
          bundle install
      - name: Pre-compile assets
        run: |
          bundle exec rails assets:precompile
      - name: migrate database
        run: |
          bundle exec rails db:migrate
      - name: Run rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432
        run: |
          bundle exec rspec
